from src.parser.creators.core.text import (
    SLOP_STOP_WORDS,
    is_russian_text,
    is_slop_or_theme_page,
    parse_published_at,
    clean_vtt_content,
)

from src.parser.creators.core.contacts import (
    EMAIL_PATTERN,
    TELEGRAM_URL_PATTERN,
    TELEGRAM_CONTEXTUAL_PATTERN,
    MENTION_PATTERN,
    URL_PATTERN,
    SOCIAL_MEDIA_DOMAINS,
    extract_emails,
    extract_telegram_handles,
    extract_mentions,
    extract_external_links,
    parse_profile_contacts,
    normalize_telegram_handle,
    is_valid_email,
    is_valid_telegram_handle,
    compile_author_metadata_dict,
)

from src.parser.creators.core.db import (
    upsert_and_deduplicate_account,
    update_account_profile_metadata,
    bulk_upsert_content,
    queue_discovered_accounts,
    queue_discovered_mentions,
    queue_single_account,
    upsert_virtual_bio_post,
)

from src.parser.creators.platforms.instagram.helpers import (
    extract_instagram_subscribers,
    extract_instagram_content_text,
    extract_instagram_published_at,
    extract_instagram_video_url,
    extract_instagram_metrics,
    build_instagram_author_metadata,
)

__all__ = [
    "SLOP_STOP_WORDS",
    "is_russian_text",
    "is_slop_or_theme_page",
    "parse_published_at",
    "clean_vtt_content",
    "EMAIL_PATTERN",
    "TELEGRAM_URL_PATTERN",
    "TELEGRAM_CONTEXTUAL_PATTERN",
    "MENTION_PATTERN",
    "URL_PATTERN",
    "SOCIAL_MEDIA_DOMAINS",
    "extract_emails",
    "extract_telegram_handles",
    "extract_mentions",
    "extract_external_links",
    "parse_profile_contacts",
    "normalize_telegram_handle",
    "is_valid_email",
    "is_valid_telegram_handle",
    "compile_author_metadata_dict",
    "upsert_and_deduplicate_account",
    "update_account_profile_metadata",
    "bulk_upsert_content",
    "queue_discovered_accounts",
    "queue_discovered_mentions",
    "queue_single_account",
    "upsert_virtual_bio_post",
    "extract_instagram_subscribers",
    "extract_instagram_content_text",
    "extract_instagram_published_at",
    "extract_instagram_video_url",
    "extract_instagram_metrics",
    "build_instagram_author_metadata",
]
